<?php
/**
 * Setup script for Sentry integration in OpenCart
 * Run this after configuring your .env file
 */

// Check if we're in the right directory
if (!file_exists('config.php') || !file_exists('system/')) {
    die("Error: This script must be run from the OpenCart root directory.\n");
}

// Load configuration
require_once('config.php');

// Check for .env file
if (!file_exists('.env')) {
    die("Error: .env file not found. Please create it from .env.example\n");
}

// Parse .env file
$envContent = file_get_contents('.env');
$envLines = explode("\n", $envContent);
$env = [];

foreach ($envLines as $line) {
    $line = trim($line);
    if (empty($line) || strpos($line, '#') === 0) continue;
    
    list($key, $value) = explode('=', $line, 2);
    $env[trim($key)] = trim($value);
}

// Check Sentry configuration
$sentryKeys = ['SENTRY_DSN', 'SENTRY_ORGANIZATION', 'SENTRY_PROJECT', 'SENTRY_AUTH_TOKEN'];
$missingKeys = [];

foreach ($sentryKeys as $key) {
    if (empty($env[$key]) || strpos($env[$key], 'your_') === 0) {
        $missingKeys[] = $key;
    }
}

if (!empty($missingKeys)) {
    echo "⚠️  Missing or invalid Sentry configuration:\n";
    foreach ($missingKeys as $key) {
        echo "   - $key\n";
    }
    echo "\nPlease update your .env file with valid Sentry credentials.\n";
    echo "Get them from: https://sentry.io/settings/projects/\n";
    exit(1);
}

echo "✅ Sentry configuration found\n";
echo "   Organization: {$env['SENTRY_ORGANIZATION']}\n";
echo "   Project: {$env['SENTRY_PROJECT']}\n";
echo "   Environment: " . ($env['SENTRY_ENVIRONMENT'] ?? 'production') . "\n\n";

// Create Sentry initialization file for OpenCart
$sentryInitContent = <<<'PHP'
<?php
/**
 * Sentry initialization for OpenCart
 * This file is auto-generated by setup-sentry-opencart.php
 */

// Only initialize if we have the autoloader
if (!file_exists(DIR_SYSTEM . '../vendor/autoload.php')) {
    return false;
}

require_once(DIR_SYSTEM . '../vendor/autoload.php');

// Load Sentry helper
if (file_exists(DIR_SYSTEM . 'helper/sentry.php')) {
    require_once(DIR_SYSTEM . 'helper/sentry.php');
}

// Initialize Sentry
if (function_exists('initSentry')) {
    $initialized = initSentry();
    
    if ($initialized && defined('OPENCART_SENTRY_DEBUG')) {
        error_log('Sentry initialized successfully for OpenCart');
    }
}

return true;
PHP;

// Write initialization file
$initFile = 'system/config/sentry.php';
if (file_put_contents($initFile, $sentryInitContent)) {
    echo "✅ Created Sentry initialization file: $initFile\n";
} else {
    echo "❌ Failed to create initialization file\n";
    exit(1);
}

// Update catalog config
$catalogConfig = 'system/config/catalog.php';
if (file_exists($catalogConfig)) {
    $configContent = file_get_contents($catalogConfig);
    
    // Check if Sentry is already included
    if (strpos($configContent, 'sentry.php') === false) {
        // Add Sentry initialization
        $sentryInclude = "\n// Sentry Error Tracking\nrequire_once(DIR_CONFIG . 'sentry.php');\n";
        
        // Find a good place to insert (after the opening PHP tag)
        $configContent = str_replace("<?php\n", "<?php\n" . $sentryInclude, $configContent);
        
        if (file_put_contents($catalogConfig, $configContent)) {
            echo "✅ Updated catalog configuration\n";
        }
    } else {
        echo "ℹ️  Sentry already configured in catalog\n";
    }
}

// Update admin config
$adminConfig = 'system/config/admin.php';
if (file_exists($adminConfig)) {
    $configContent = file_get_contents($adminConfig);
    
    // Check if Sentry is already included
    if (strpos($configContent, 'sentry.php') === false) {
        // Add Sentry initialization
        $sentryInclude = "\n// Sentry Error Tracking\nrequire_once(DIR_CONFIG . 'sentry.php');\n";
        
        // Find a good place to insert (after the opening PHP tag)
        $configContent = str_replace("<?php\n", "<?php\n" . $sentryInclude, $configContent);
        
        if (file_put_contents($adminConfig, $configContent)) {
            echo "✅ Updated admin configuration\n";
        }
    } else {
        echo "ℹ️  Sentry already configured in admin\n";
    }
}

echo "\n🎉 Sentry integration setup complete!\n\n";
echo "Next steps:\n";
echo "1. Install Composer dependencies:\n";
echo "   docker compose exec opencart composer install\n\n";
echo "2. Rebuild and restart Docker containers:\n";
echo "   docker compose down\n";
echo "   docker compose build --no-cache\n";
echo "   docker compose up -d\n\n";
echo "3. Test the integration:\n";
echo "   Visit http://localhost:8080/test-sentry.php\n\n";
echo "4. Start MCP Server (optional):\n";
echo "   npm run sentry-mcp\n";
?>